DROP TABLE IF EXISTS PUBLIC.PHONES;
DROP TABLE IF EXISTS PUBLIC.USERS;

CREATE TABLE PUBLIC.USERS (
	USER_ID UUID NOT NULL,
	EMAIL CHARACTER VARYING(50) NOT NULL,
	NAME CHARACTER VARYING(255) NOT NULL,
	PASSWORD CHARACTER VARYING(255) NOT NULL,
	IS_ACTIVE BOOLEAN,
	CREATED_DATE TIMESTAMP,
	LAST_LOGIN TIMESTAMP,
	MODIFIED_DATE TIMESTAMP,
	TOKEN CHARACTER VARYING(255),
	CONSTRAINT UN_EMAIL UNIQUE (EMAIL),
	CONSTRAINT PK_USERID PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX INDEX_UN_EMAIL ON PUBLIC.USERS (EMAIL);
CREATE UNIQUE INDEX INDEX_PK_USERID ON PUBLIC.USERS (USER_ID);


CREATE TABLE PUBLIC.PHONES (
	PHONE_ID UUID NOT NULL,
	USER_ID UUID,
	CITY_CODE CHARACTER VARYING(255),
	COUNTRY_CODE CHARACTER VARYING(255),
	"NUMBER" CHARACTER VARYING(255),
	CONSTRAINT CONSTRAINT_8 PRIMARY KEY (PHONE_ID)
);
CREATE INDEX INDEX_PHONE_USERID ON PUBLIC.PHONES (USER_ID);
CREATE UNIQUE INDEX INDEX_UN_PHONEID ON PUBLIC.PHONES (PHONE_ID);
-- PUBLIC.PHONES foreign keys
ALTER TABLE PUBLIC.PHONES ADD CONSTRAINT FK_PHONEID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;